[domain_controllers]
dc01 ansible_host=10.10.1.10

[member_servers]
client01 ansible_host=10.10.2.20

[windows:children]
domain_controllers
member_servers

[windows:vars]
ansible_user=Administrator
# Note: The password will be passed at runtime or via terraform.tfvars
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore